#152 Extensions enhancements
spideythewebhead/data_class_plugin pull request #153
Opened 2022-12-09 00:22 UTC by nikosportolos

- Created AnnotationTypes enum
- Created AnnotationArgs interface with implementations:
  - DataClassAnnotationArgs
  - EnumAnnotationArgs
  - UnionAnnotationArgs
- Modified analysis_extensions
- Modified annotation_extensions

2022-12-09 01:34 UTC, nikosportolos commented
@spideythewebhead  This PR requires #151 to be approved & merged first.
I created 2 separate PRs for less merge conflicts and easier reviews.

2022-12-09 22:21 UTC, spideythewebhead requested changes

2022-12-09 22:21 UTC, spideythewebhead commented on lib/src/annotations/constants.dart
> +enum AnnotationTypes {
Change the plural to singular , `AnnotationTypes` -> `AnnotationType` for all the classes

2022-12-10 09:57 UTC, spideythewebhead approved these changes

2022-12-10 09:58 UTC, merged